"""Textos de la web conjunta: Psicoanálisis en Barcelona."""
from .common import SOL, NAHUEL, URLS, wa, mail

LANGS = ['es', 'en', 'pt']

ES = {
    'scene': {'label': 'Dos recorridos, una escucha compartida', 'lines': ['Dos recorridos.', 'Una escucha <em>compartida.</em>', 'Un lugar <em>para empezar.</em>'], 'sub': 'Sol Galiana · Nahuel Ponce'},
    'marquee': ['Escucha', 'Singularidad', 'Profundidad', 'Gràcia', 'Sants', 'Online', 'Español', 'English', 'Português'],
    'meta': {
        'title': 'Psicoterapia psicoanalítica en Barcelona y online | Psicoanálisis en Barcelona',
        'description': 'Psicólogos en Barcelona (Gràcia y Sants) y online, con orientación psicoanalítica. Ansiedad, vínculos, duelo, identidad y procesos migratorios. Atención en español, inglés y portugués.',
    },
    'nav': [
        {'href': '#enfoque', 'label': 'Enfoque'},
        {'href': '#equipo', 'label': 'Profesionales'},
        {'href': '#servicios', 'label': 'Servicios'},
        {'href': '#consultorios', 'label': 'Consultorios'},
        {'href': '/blog/', 'label': 'Blog'},
        {'href': '#preguntas', 'label': 'Preguntas'},
    ],
    'cta': {'href': '#contacto', 'label': 'Primera consulta'},
    'hero': {
        'eyebrow': 'Orientación psicoanalítica · Adultos y jóvenes',
        'h1': 'Psicoterapia <em>en Barcelona</em> y online',
        'rotate_intro': 'Un lugar para',
        'rotate': [
            'lo que todavía no sabes cómo nombrar.',
            'aquello que se repite.',
            'empezar de nuevo lejos de casa.',
            'atravesar una pérdida.',
            'pensar con calma lo que estás viviendo.',
        ],
        'lead': 'Acompañamos a adultos y jóvenes en procesos relacionados con la ansiedad, los vínculos, la identidad, las pérdidas y los momentos de cambio, con especial experiencia en personas migrantes, expatriadas y estudiantes internacionales.',
        'primary': 'Pedir una primera consulta',
        'secondary': 'Conocer al equipo',
        'img_alt': 'Consultorio con la frase «Aquí y ahora» en la pared, un sillón y plantas',
        'caption': 'Aquí y ahora',
        'facts': [
            {'k': 'Gràcia · Sants', 'v': 'Consultorios en Barcelona'},
            {'k': 'Online', 'v': 'Desde donde estés'},
            {'k': 'ES · EN · PT', 'v': 'Tres idiomas'},
            {'k': '45 min', 'v': 'Sesión individual'},
        ],
    },
    'approach': {
        'kicker': 'Nuestro enfoque',
        'title': 'No hay una fórmula general para una historia singular.',
        'lead': 'Entendemos la psicoterapia como un espacio en el que poder detenerse y profundizar en aquello que está generando malestar.',
        'paras': [
            'Más que centrarnos únicamente en eliminar un síntoma, buscamos comprender qué lugar ocupa dentro de la experiencia particular de cada persona. La ansiedad, la angustia, un conflicto, una pérdida o una dificultad que se repite pueden ser el punto de partida de un proceso más amplio de comprensión.',
            'Cada tratamiento se construye de manera individual. No todas las personas llegan por los mismos motivos ni necesitan recorrer el mismo camino: por eso respetamos los tiempos, la historia y las circunstancias de cada paciente.',
        ],
        'pillars': [
            {'t': 'Escucha', 'd': 'Un espacio profesional, cercano y respetuoso para hablar con libertad.'},
            {'t': 'Singularidad', 'd': 'Sin soluciones predeterminadas: cada proceso se construye a medida.'},
            {'t': 'Profundidad', 'd': 'Comprender cómo se articula el malestar con tu historia y tus vínculos.'},
        ],
    },
    'reasons': {
        'kicker': 'Motivos de consulta',
        'title': 'A veces hay un motivo claro. <em>A veces sólo algo que insiste.</em>',
        'lead': 'Trabajamos principalmente con personas adultas y jóvenes que atraviesan diferentes momentos y situaciones vitales.',
        'items': [
            'Ansiedad, angustia y estrés',
            'Dificultades en las relaciones y conflictos vinculares',
            'Autoestima e identidad',
            'Dificultades relacionadas con el apego',
            'Duelo, pérdidas y separaciones',
            'Crisis personales y momentos de cambio',
            'Experiencias traumáticas',
            'Sensación de bloqueo o situaciones que se repiten',
            'Procesos migratorios',
            'Adaptación a un nuevo país o cultura',
            'Soledad y desarraigo',
            'Estudios e inicio de la vida profesional',
        ],
    },
    'migration': {
        'kicker': 'Vivir lejos del lugar de origen',
        'title': 'Mudarse no es sólo cambiar de lugar.',
        'paras': [
            'Comenzar una vida en otro país puede implicar entusiasmo y nuevas posibilidades, pero también pérdidas, contradicciones y preguntas difíciles de compartir con quienes no están atravesando la misma experiencia.',
            'Tenemos especial interés y experiencia en el acompañamiento de personas migrantes, expatriadas y estudiantes internacionales: la identidad, el sentido de pertenencia, la distancia con los vínculos de origen, el choque cultural y la construcción de nuevos proyectos.',
        ],
        'quote': 'La terapia puede ser un espacio para elaborar esos cambios y encontrar una manera propia de transitar esa etapa.',
        'words': ['origen', 'tránsito', 'pertenencia'],
    },
    'team': {
        'kicker': 'Profesionales',
        'title': 'Dos recorridos. <em>Una forma compartida de escuchar.</em>',
        'lead': 'Ambos contamos con títulos homologados en España, formación de posgrado en psicoanálisis y más de siete años de experiencia clínica. Puedes elegir al profesional, la modalidad y el idioma que mejor se adapten a ti.',
        'web': 'Ver su web',
        'write': 'Escribir',
        'people': [
            {
                'key': 'sol', 'name': SOL['name'], 'role': 'Psicóloga clínica',
                'img': 'sol', 'img_alt': 'Retrato de Sol Galiana, psicóloga',
                'text': 'Máster en Psicoanálisis (Clínica de Adultos). Trabaja especialmente con personas internacionales y expatriadas: identidad, choque cultural, nostalgia, soledad, autoestima, vínculos y duelos. Espacio LGBTQ+ friendly.',
                'langs': ['Español', 'English'],
                'url': URLS['sol'],
                'wa': wa(SOL['phone'], 'Hola Sol, te escribo desde la web de Psicoanálisis en Barcelona. Me gustaría consultar por una primera sesión.'),
            },
            {
                'key': 'nahuel', 'name': NAHUEL['name'], 'role': 'Psicólogo General Sanitario',
                'img': 'nahuel', 'img_alt': 'Retrato en blanco y negro de Nahuel Ponce, psicólogo',
                'text': 'Posgrado en Clínica Psicoanalítica (Instituto Fernando Ulloa). Trabaja principalmente con adultos: ansiedad, angustia, duelo, apego, conflictos relacionales, trauma y manifestaciones psicosomáticas.',
                'langs': ['Español', 'Português'],
                'url': URLS['nahuel'],
                'wa': wa(NAHUEL['phone'], 'Hola Nahuel, te escribo desde la web de Psicoanálisis en Barcelona. Me gustaría consultar por una primera sesión.'),
            },
        ],
    },
    'services': {
        'kicker': 'Servicios',
        'title': 'Presencial en Barcelona. <em>Online desde donde estés.</em>',
        'items': [
            {'name': 'Psicoterapia individual', 'meta': '45 minutos · Presencial u online', 'text': 'Para adultos y jóvenes. Un proceso a tu medida, en español, inglés o portugués.'},
            {'name': 'Sesión con tarifa flexible', 'meta': '1 hora · Desde 40 €', 'text': 'Una opción accesible para que el coste no sea un impedimento para empezar.'},
            {'name': 'Supervisión clínica individual', 'meta': '1 hora · Presencial u online', 'text': 'Análisis y construcción de casos clínicos para profesionales de la salud mental.'},
            {'name': 'Supervisión grupal', 'meta': '2 horas · Presencial u online', 'text': 'Para personas en formación psicoanalítica. Servicio personalizado de análisis de casos.'},
        ],
        'note': 'Consulta honorarios y disponibilidad escribiendo directamente a cada profesional.',
    },
    'first': {
        'kicker': 'Primera consulta',
        'title': 'No es necesario tener todo claro para empezar.',
        'paras': [
            'Algunas personas llegan con un motivo concreto: ansiedad, una pérdida, una separación, un conflicto o una situación que se ha vuelto difícil de sostener.',
            'Otras simplemente sienten que algo no está funcionando como quisieran, que determinadas situaciones se repiten o que necesitan un espacio para pensar lo que están viviendo.',
            'La primera consulta permite empezar a poner en palabras estas cuestiones, conocer nuestra manera de trabajar y valorar cómo iniciar un proceso terapéutico.',
        ],
        'steps': [
            {'t': 'Escribes', 'd': 'Por WhatsApp o email, con pocas palabras alcanza.'},
            {'t': 'Coordinamos', 'd': 'Elegimos día, modalidad e idioma.'},
            {'t': 'Conversamos', 'd': 'Una primera sesión para conocernos y empezar.'},
        ],
        'cta': 'Elegir con quién empezar',
        'img_alt': 'Sol Galiana en su consultorio, escuchando',
    },
    'places': {
        'kicker': 'Consultorios',
        'title': 'Dos espacios en Barcelona.',
        'online_zone': 'Online',
        'online_title': 'Desde donde estés',
        'online_detail': 'Videollamada en español, inglés o portugués',
        'img_alt': 'Sala de espera luminosa con sofá gris y cojines',
    },
    'blog': {
        'kicker': 'Blog',
        'title': 'Escritos para pensar.',
        'more': 'Ver todos los artículos',
        'read': 'Leer',
        'note': '',
    },
    'faq': {
        'kicker': 'Preguntas frecuentes',
        'title': 'Información para orientarte.',
        'items': [
            {'q': '¿Qué es la psicoterapia psicoanalítica?', 'a': 'Es una forma de psicoterapia que, además de atender el malestar actual, busca comprender cómo se relaciona con la historia, los vínculos y la experiencia singular de cada persona. No se trata de aplicar una técnica igual para todos, sino de construir un proceso a partir de lo que cada uno trae.'},
            {'q': '¿Atienden de forma presencial en Barcelona?', 'a': 'Sí. Atendemos en dos consultorios de Barcelona, en Gràcia (Carrer de Badia, 24) y en Sants (Carrer de València, 28), y también ofrecemos sesiones online.'},
            {'q': '¿En qué idiomas puedo hacer terapia?', 'a': 'Entre ambos profesionales, las sesiones pueden realizarse en español, inglés y portugués. Sol Galiana atiende en español e inglés; Nahuel Ponce, en español y portugués.'},
            {'q': '¿Trabajan con expatriados y estudiantes internacionales?', 'a': 'Sí. Tenemos experiencia acompañando procesos migratorios, adaptación cultural, identidad, soledad, desarraigo y la construcción de nuevos proyectos personales.'},
            {'q': '¿Cuánto dura una sesión y cuánto cuesta?', 'a': 'La sesión individual dura 45 minutos. Además existe una modalidad con tarifa flexible, de una hora, desde 40 €. Para conocer los honorarios exactos y la disponibilidad, escribe directamente al profesional.'},
            {'q': '¿Cómo elijo al profesional?', 'a': 'Puedes tener en cuenta el idioma, la modalidad, la disponibilidad y la presentación de cada uno. Si dudas, escríbenos y te orientamos.'},
            {'q': '¿Tengo que saber explicar lo que me pasa?', 'a': 'No. La primera consulta también sirve para empezar a encontrar palabras para eso que preocupa o genera malestar.'},
        ],
    },
    'contact': {
        'kicker': 'Contacto directo',
        'title': 'Elige con quién quieres empezar.',
        'lead': 'Escríbenos por WhatsApp o email para coordinar una primera consulta. Respondemos personalmente.',
        'people': [
            {'name': SOL['name'], 'langs': 'Español · English', 'wa': wa(SOL['phone'], 'Hola Sol, me gustaría coordinar una primera consulta.'), 'wa_label': 'WhatsApp · ' + SOL['phone_display'], 'mail': mail(SOL['email'], 'Primera consulta'), 'email': SOL['email'], 'track': 'sol'},
            {'name': NAHUEL['name'], 'langs': 'Español · Português', 'wa': wa(NAHUEL['phone'], 'Hola Nahuel, me gustaría coordinar una primera consulta.'), 'wa_label': 'WhatsApp · ' + NAHUEL['phone_display'], 'mail': mail(NAHUEL['email'], 'Primera consulta'), 'email': NAHUEL['email'], 'track': 'nahuel'},
        ],
    },
    'footer': {
        'tagline': 'Psicoterapia de orientación psicoanalítica en Barcelona y online.',
        'legal': 'Profesionales con titulación homologada para ejercer en España.',
    },
    'dock': {'label': 'Pedir primera consulta', 'href': '#contacto'},
}

EN = {
    'scene': {'label': 'Two paths, one shared way of listening', 'lines': ['Two paths.', 'One shared <em>way of listening.</em>', 'A place <em>to begin.</em>'], 'sub': 'Sol Galiana · Nahuel Ponce'},
    'marquee': ['Listening', 'Singularity', 'Depth', 'Gràcia', 'Sants', 'Online', 'English', 'Español', 'Português'],
    'meta': {
        'title': 'Psychoanalytic psychotherapy in Barcelona and online | Psicoanálisis en Barcelona',
        'description': 'English-speaking psychologists in Barcelona (Gràcia and Sants) and online, with a psychoanalytic approach. Anxiety, relationships, grief, identity and life abroad. Sessions in English, Spanish and Portuguese.',
    },
    'nav': [
        {'href': '#enfoque', 'label': 'Approach'},
        {'href': '#equipo', 'label': 'Therapists'},
        {'href': '#servicios', 'label': 'Services'},
        {'href': '#consultorios', 'label': 'Locations'},
        {'href': '/blog/', 'label': 'Blog (ES)'},
        {'href': '#preguntas', 'label': 'FAQ'},
    ],
    'cta': {'href': '#contacto', 'label': 'First session'},
    'hero': {
        'eyebrow': 'Psychoanalytic approach · Adults and young people',
        'h1': 'Therapy <em>in Barcelona</em> and online',
        'rotate_intro': 'A place for',
        'rotate': [
            'what you can’t quite put into words yet.',
            'the things that keep repeating.',
            'starting over far from home.',
            'going through a loss.',
            'slowing down and thinking things through.',
        ],
        'lead': 'We work with adults and young people through anxiety, relationships, identity, loss and times of change — with particular experience supporting migrants, expats and international students.',
        'primary': 'Book a first session',
        'secondary': 'Meet the team',
        'img_alt': 'Therapy room with the words “Aquí y ahora” (here and now) on the wall, an armchair and plants',
        'caption': 'Here and now',
        'facts': [
            {'k': 'Gràcia · Sants', 'v': 'Offices in Barcelona'},
            {'k': 'Online', 'v': 'Wherever you are'},
            {'k': 'EN · ES · PT', 'v': 'Three languages'},
            {'k': '45 min', 'v': 'Individual session'},
        ],
    },
    'approach': {
        'kicker': 'Our approach',
        'title': 'There is no general formula for a singular story.',
        'lead': 'We see therapy as a space where you can pause and look more deeply at whatever is causing you distress.',
        'paras': [
            'Rather than focusing only on getting rid of a symptom, we try to understand the place it holds in each person’s particular experience. Anxiety, distress, a conflict, a loss or a difficulty that keeps coming back can be the starting point of a broader process of understanding.',
            'Every treatment is built individually. Not everyone comes for the same reasons or needs to follow the same path — so we respect each person’s pace, history and circumstances.',
        ],
        'pillars': [
            {'t': 'Listening', 'd': 'A professional, warm and respectful space to speak freely.'},
            {'t': 'Singularity', 'd': 'No ready-made solutions: each process is shaped around you.'},
            {'t': 'Depth', 'd': 'Understanding how distress connects with your history and relationships.'},
        ],
    },
    'reasons': {
        'kicker': 'Reasons people come',
        'title': 'Sometimes there’s a clear reason. <em>Sometimes just something that persists.</em>',
        'lead': 'We mainly work with adults and young people going through different moments and life situations.',
        'items': [
            'Anxiety, distress and stress',
            'Relationship difficulties and conflicts',
            'Self-esteem and identity',
            'Attachment-related difficulties',
            'Grief, loss and separation',
            'Personal crises and times of change',
            'Traumatic experiences',
            'Feeling stuck or caught in repeating patterns',
            'Migration processes',
            'Adapting to a new country or culture',
            'Loneliness and uprootedness',
            'Studies and starting a professional life',
        ],
    },
    'migration': {
        'kicker': 'Living far from where you started',
        'title': 'Moving abroad is not just changing places.',
        'paras': [
            'Starting a life in another country can bring excitement and new possibilities — but also losses, contradictions and questions that are hard to share with people who aren’t going through the same thing.',
            'We have a particular interest and experience in supporting migrants, expats and international students: identity, belonging, distance from family and friends back home, culture shock and building new projects.',
        ],
        'quote': 'Therapy can become a space to work through those changes and find your own way of living this chapter.',
        'words': ['origin', 'transit', 'belonging'],
    },
    'team': {
        'kicker': 'Therapists',
        'title': 'Two paths. <em>A shared way of listening.</em>',
        'lead': 'We both hold degrees recognised in Spain, postgraduate training in psychoanalysis and over seven years of clinical experience. You can choose the therapist, format and language that suit you best.',
        'web': 'Visit website',
        'write': 'Message',
        'people': [
            {
                'key': 'sol', 'name': SOL['name'], 'role': 'Clinical psychologist',
                'img': 'sol', 'img_alt': 'Portrait of Sol Galiana, psychologist',
                'text': 'Master’s in Psychoanalysis (Adult Clinical Practice). Works especially with international people and expats: identity, culture shock, homesickness, loneliness, self-esteem, relationships and grief. LGBTQ+ affirming.',
                'langs': ['English', 'Español'],
                'url': URLS['sol'] + '/en/',
                'wa': wa(SOL['phone'], 'Hi Sol, I found you through Psicoanálisis en Barcelona. I’d like to ask about a first session.'),
            },
            {
                'key': 'nahuel', 'name': NAHUEL['name'], 'role': 'Psychologist (Psicólogo General Sanitario)',
                'img': 'nahuel', 'img_alt': 'Black and white portrait of Nahuel Ponce, psychologist',
                'text': 'Postgraduate in Psychoanalytic Clinical Practice (Instituto Fernando Ulloa). Works mainly with adults: anxiety, distress, grief, attachment, relationship conflicts, trauma and psychosomatic symptoms. Sessions in Spanish and Portuguese.',
                'langs': ['Español', 'Português'],
                'url': URLS['nahuel'] + '/pt/',
                'wa': wa(NAHUEL['phone'], 'Hi Nahuel, I found you through Psicoanálisis en Barcelona. I’d like to ask about a first session.'),
            },
        ],
    },
    'services': {
        'kicker': 'Services',
        'title': 'In person in Barcelona. <em>Online wherever you are.</em>',
        'items': [
            {'name': 'Individual therapy', 'meta': '45 minutes · In person or online', 'text': 'For adults and young people. A process shaped around you, in English, Spanish or Portuguese.'},
            {'name': 'Sliding-scale session', 'meta': '1 hour · From €40', 'text': 'An accessible option so that cost doesn’t stand in the way of getting started.'},
            {'name': 'Individual clinical supervision', 'meta': '1 hour · In person or online', 'text': 'Case analysis and case formulation for mental health professionals.'},
            {'name': 'Group supervision', 'meta': '2 hours · In person or online', 'text': 'For people in psychoanalytic training. A tailored case-discussion service.'},
        ],
        'note': 'For fees and availability, message each therapist directly.',
    },
    'first': {
        'kicker': 'First session',
        'title': 'You don’t need to have it all figured out to start.',
        'paras': [
            'Some people come with a specific reason: anxiety, a loss, a breakup, a conflict or a situation that has become hard to bear.',
            'Others simply feel that something isn’t working the way they’d like, that certain situations keep repeating, or that they need a space to think about what they’re going through.',
            'The first session is a chance to start putting these things into words, get to know how we work and consider how to begin a therapeutic process.',
        ],
        'steps': [
            {'t': 'You write', 'd': 'By WhatsApp or email — a few words are enough.'},
            {'t': 'We arrange', 'd': 'Day, format and language.'},
            {'t': 'We talk', 'd': 'A first session to get to know each other.'},
        ],
        'cta': 'Choose who to start with',
        'img_alt': 'Sol Galiana in her office, listening',
    },
    'places': {
        'kicker': 'Locations',
        'title': 'Two spaces in Barcelona.',
        'online_zone': 'Online',
        'online_title': 'Wherever you are',
        'online_detail': 'Video sessions in English, Spanish or Portuguese',
        'img_alt': 'Bright waiting room with a grey sofa and cushions',
    },
    'blog': {
        'kicker': 'Blog',
        'title': 'Writing to think with.',
        'more': 'See all articles',
        'read': 'Read',
        'note': 'Articles currently available in Spanish.',
    },
    'faq': {
        'kicker': 'FAQ',
        'title': 'Things you might want to know.',
        'items': [
            {'q': 'What is psychoanalytic psychotherapy?', 'a': 'It is a form of therapy that, as well as addressing current distress, seeks to understand how it relates to each person’s history, relationships and unique experience. It isn’t about applying the same technique to everyone, but about building a process from what each person brings.'},
            {'q': 'Do you offer in-person sessions in Barcelona?', 'a': 'Yes. We see clients at two offices in Barcelona — Gràcia (Carrer de Badia, 24) and Sants (Carrer de València, 28) — and we also offer online sessions.'},
            {'q': 'Which languages can I do therapy in?', 'a': 'Between the two of us, sessions are available in English, Spanish and Portuguese. Sol Galiana works in English and Spanish; Nahuel Ponce in Spanish and Portuguese.'},
            {'q': 'Do you work with expats and international students?', 'a': 'Yes. We have experience supporting migration, cultural adaptation, identity, loneliness, uprootedness and building a new life project.'},
            {'q': 'How long is a session and how much does it cost?', 'a': 'An individual session lasts 45 minutes. There is also a one-hour sliding-scale option from €40. For exact fees and availability, message the therapist directly.'},
            {'q': 'How do I choose a therapist?', 'a': 'Consider language, format, availability and how each of us presents our work. If you’re unsure, write to us and we’ll help you decide.'},
            {'q': 'Do I need to be able to explain what’s happening to me?', 'a': 'No. The first session is also a place to begin finding words for whatever is worrying or troubling you.'},
        ],
    },
    'contact': {
        'kicker': 'Get in touch',
        'title': 'Choose who you’d like to start with.',
        'lead': 'Message us on WhatsApp or by email to arrange a first session. We reply personally.',
        'people': [
            {'name': SOL['name'], 'langs': 'English · Español', 'wa': wa(SOL['phone'], 'Hi Sol, I’d like to arrange a first session.'), 'wa_label': 'WhatsApp · ' + SOL['phone_display'], 'mail': mail(SOL['email'], 'First session'), 'email': SOL['email'], 'track': 'sol'},
            {'name': NAHUEL['name'], 'langs': 'Español · Português', 'wa': wa(NAHUEL['phone'], 'Hi Nahuel, I’d like to arrange a first session.'), 'wa_label': 'WhatsApp · ' + NAHUEL['phone_display'], 'mail': mail(NAHUEL['email'], 'First session'), 'email': NAHUEL['email'], 'track': 'nahuel'},
        ],
    },
    'footer': {
        'tagline': 'Psychoanalytic psychotherapy in Barcelona and online.',
        'legal': 'Psychologists with degrees officially recognised in Spain.',
    },
    'dock': {'label': 'Book a first session', 'href': '#contacto'},
}

PT = {
    'scene': {'label': 'Dois percursos, uma escuta compartilhada', 'lines': ['Dois percursos.', 'Uma escuta <em>compartilhada.</em>', 'Um lugar <em>para começar.</em>'], 'sub': 'Nahuel Ponce · Sol Galiana'},
    'marquee': ['Escuta', 'Singularidade', 'Profundidade', 'Gràcia', 'Sants', 'Online', 'Português', 'Español', 'English'],
    'meta': {
        'title': 'Psicoterapia psicanalítica em Barcelona e online | Psicoanálisis en Barcelona',
        'description': 'Psicólogos em Barcelona (Gràcia e Sants) e online, com orientação psicanalítica. Ansiedade, relações, luto, identidade e processos migratórios. Atendimento em português, espanhol e inglês.',
    },
    'nav': [
        {'href': '#enfoque', 'label': 'Abordagem'},
        {'href': '#equipo', 'label': 'Profissionais'},
        {'href': '#servicios', 'label': 'Serviços'},
        {'href': '#consultorios', 'label': 'Consultórios'},
        {'href': '/blog/', 'label': 'Blog (ES)'},
        {'href': '#preguntas', 'label': 'Perguntas'},
    ],
    'cta': {'href': '#contacto', 'label': 'Primeira consulta'},
    'hero': {
        'eyebrow': 'Orientação psicanalítica · Adultos e jovens',
        'h1': 'Psicoterapia <em>em Barcelona</em> e online',
        'rotate_intro': 'Um lugar para',
        'rotate': [
            'o que você ainda não sabe nomear.',
            'aquilo que se repete.',
            'recomeçar longe de casa.',
            'atravessar uma perda.',
            'pensar com calma no que está vivendo.',
        ],
        'lead': 'Acompanhamos adultos e jovens em processos ligados à ansiedade, às relações, à identidade, às perdas e aos momentos de mudança, com especial experiência com pessoas migrantes, expatriadas e estudantes internacionais.',
        'primary': 'Marcar uma primeira consulta',
        'secondary': 'Conhecer a equipe',
        'img_alt': 'Consultório com a frase «Aquí y ahora» (aqui e agora) na parede, uma poltrona e plantas',
        'caption': 'Aqui e agora',
        'facts': [
            {'k': 'Gràcia · Sants', 'v': 'Consultórios em Barcelona'},
            {'k': 'Online', 'v': 'De onde você estiver'},
            {'k': 'PT · ES · EN', 'v': 'Três idiomas'},
            {'k': '45 min', 'v': 'Sessão individual'},
        ],
    },
    'approach': {
        'kicker': 'Nossa abordagem',
        'title': 'Não existe uma fórmula geral para uma história singular.',
        'lead': 'Entendemos a psicoterapia como um espaço onde é possível parar e aprofundar aquilo que está causando sofrimento.',
        'paras': [
            'Mais do que nos concentrarmos apenas em eliminar um sintoma, buscamos compreender que lugar ele ocupa na experiência particular de cada pessoa. A ansiedade, a angústia, um conflito, uma perda ou uma dificuldade que se repete podem ser o ponto de partida de um processo mais amplo de compreensão.',
            'Cada tratamento é construído de forma individual. Nem todas as pessoas chegam pelos mesmos motivos nem precisam percorrer o mesmo caminho: por isso respeitamos o tempo, a história e as circunstâncias de cada paciente.',
        ],
        'pillars': [
            {'t': 'Escuta', 'd': 'Um espaço profissional, próximo e respeitoso para falar com liberdade.'},
            {'t': 'Singularidade', 'd': 'Sem soluções prontas: cada processo é construído sob medida.'},
            {'t': 'Profundidade', 'd': 'Compreender como o sofrimento se articula com sua história e seus vínculos.'},
        ],
    },
    'reasons': {
        'kicker': 'Motivos de consulta',
        'title': 'Às vezes há um motivo claro. <em>Às vezes só algo que insiste.</em>',
        'lead': 'Trabalhamos principalmente com adultos e jovens que atravessam diferentes momentos e situações de vida.',
        'items': [
            'Ansiedade, angústia e estresse',
            'Dificuldades nas relações e conflitos',
            'Autoestima e identidade',
            'Dificuldades ligadas ao apego',
            'Luto, perdas e separações',
            'Crises pessoais e momentos de mudança',
            'Experiências traumáticas',
            'Sensação de bloqueio ou situações que se repetem',
            'Processos migratórios',
            'Adaptação a um novo país ou cultura',
            'Solidão e desenraizamento',
            'Estudos e início da vida profissional',
        ],
    },
    'migration': {
        'kicker': 'Viver longe do lugar de origem',
        'title': 'Mudar de país não é só mudar de lugar.',
        'paras': [
            'Começar uma vida em outro país pode trazer entusiasmo e novas possibilidades, mas também perdas, contradições e perguntas difíceis de compartilhar com quem não está passando pela mesma experiência.',
            'Temos especial interesse e experiência no acompanhamento de pessoas migrantes, expatriadas e estudantes internacionais: identidade, pertencimento, distância dos vínculos de origem, choque cultural e construção de novos projetos.',
        ],
        'quote': 'A terapia pode ser um espaço para elaborar essas mudanças e encontrar uma maneira própria de atravessar essa etapa.',
        'words': ['origem', 'trânsito', 'pertencimento'],
    },
    'team': {
        'kicker': 'Profissionais',
        'title': 'Dois percursos. <em>Uma forma compartilhada de escutar.</em>',
        'lead': 'Ambos temos diplomas homologados na Espanha, formação de pós-graduação em psicanálise e mais de sete anos de experiência clínica. Você pode escolher o profissional, a modalidade e o idioma que mais combinam com você.',
        'web': 'Ver site',
        'write': 'Escrever',
        'people': [
            {
                'key': 'nahuel', 'name': NAHUEL['name'], 'role': 'Psicólogo (Psicólogo General Sanitario)',
                'img': 'nahuel', 'img_alt': 'Retrato em preto e branco de Nahuel Ponce, psicólogo',
                'text': 'Pós-graduação em Clínica Psicanalítica (Instituto Fernando Ulloa). Atende principalmente adultos: ansiedade, angústia, luto, apego, conflitos nas relações, trauma e manifestações psicossomáticas. Atendimento em português e espanhol.',
                'langs': ['Português', 'Español'],
                'url': URLS['nahuel'] + '/pt/',
                'wa': wa(NAHUEL['phone'], 'Olá Nahuel, encontrei você pelo site Psicoanálisis en Barcelona. Gostaria de marcar uma primeira consulta.'),
            },
            {
                'key': 'sol', 'name': SOL['name'], 'role': 'Psicóloga clínica',
                'img': 'sol', 'img_alt': 'Retrato de Sol Galiana, psicóloga',
                'text': 'Mestrado em Psicanálise (Clínica de Adultos). Trabalha especialmente com pessoas internacionais e expatriadas: identidade, choque cultural, saudade, solidão, autoestima, relações e luto. Atendimento em espanhol e inglês.',
                'langs': ['Español', 'English'],
                'url': URLS['sol'],
                'wa': wa(SOL['phone'], 'Hola Sol, te encontré a través de Psicoanálisis en Barcelona. Me gustaría consultar por una primera sesión.'),
            },
        ],
    },
    'services': {
        'kicker': 'Serviços',
        'title': 'Presencial em Barcelona. <em>Online de onde você estiver.</em>',
        'items': [
            {'name': 'Psicoterapia individual', 'meta': '45 minutos · Presencial ou online', 'text': 'Para adultos e jovens. Um processo sob medida, em português, espanhol ou inglês.'},
            {'name': 'Sessão com valor flexível', 'meta': '1 hora · A partir de 40 €', 'text': 'Uma opção acessível para que o custo não seja um impedimento para começar.'},
            {'name': 'Supervisão clínica individual', 'meta': '1 hora · Presencial ou online', 'text': 'Análise e construção de casos clínicos para profissionais de saúde mental.'},
            {'name': 'Supervisão em grupo', 'meta': '2 horas · Presencial ou online', 'text': 'Para pessoas em formação psicanalítica. Serviço personalizado de análise de casos.'},
        ],
        'note': 'Consulte valores e disponibilidade diretamente com cada profissional.',
    },
    'first': {
        'kicker': 'Primeira consulta',
        'title': 'Não é preciso ter tudo claro para começar.',
        'paras': [
            'Algumas pessoas chegam com um motivo concreto: ansiedade, uma perda, uma separação, um conflito ou uma situação que ficou difícil de sustentar.',
            'Outras simplesmente sentem que algo não está funcionando como gostariam, que certas situações se repetem ou que precisam de um espaço para pensar no que estão vivendo.',
            'A primeira consulta permite começar a colocar essas questões em palavras, conhecer nossa forma de trabalhar e avaliar como iniciar um processo terapêutico.',
        ],
        'steps': [
            {'t': 'Você escreve', 'd': 'Por WhatsApp ou e-mail; poucas palavras bastam.'},
            {'t': 'Combinamos', 'd': 'Dia, modalidade e idioma.'},
            {'t': 'Conversamos', 'd': 'Uma primeira sessão para nos conhecermos.'},
        ],
        'cta': 'Escolher com quem começar',
        'img_alt': 'Sol Galiana em seu consultório, escutando',
    },
    'places': {
        'kicker': 'Consultórios',
        'title': 'Dois espaços em Barcelona.',
        'online_zone': 'Online',
        'online_title': 'De onde você estiver',
        'online_detail': 'Videochamada em português, espanhol ou inglês',
        'img_alt': 'Sala de espera iluminada com sofá cinza e almofadas',
    },
    'blog': {
        'kicker': 'Blog',
        'title': 'Textos para pensar.',
        'more': 'Ver todos os artigos',
        'read': 'Ler',
        'note': 'Artigos disponíveis em espanhol.',
    },
    'faq': {
        'kicker': 'Perguntas frequentes',
        'title': 'Informações para te orientar.',
        'items': [
            {'q': 'O que é a psicoterapia psicanalítica?', 'a': 'É uma forma de psicoterapia que, além de cuidar do sofrimento atual, busca compreender como ele se relaciona com a história, os vínculos e a experiência singular de cada pessoa. Não se trata de aplicar a mesma técnica para todos, mas de construir um processo a partir do que cada um traz.'},
            {'q': 'Vocês atendem presencialmente em Barcelona?', 'a': 'Sim. Atendemos em dois consultórios em Barcelona, em Gràcia (Carrer de Badia, 24) e em Sants (Carrer de València, 28), e também oferecemos sessões online.'},
            {'q': 'Em quais idiomas posso fazer terapia?', 'a': 'Entre os dois profissionais, as sessões podem ser em português, espanhol e inglês. Nahuel Ponce atende em português e espanhol; Sol Galiana, em espanhol e inglês.'},
            {'q': 'Vocês trabalham com expatriados e estudantes internacionais?', 'a': 'Sim. Temos experiência com processos migratórios, adaptação cultural, identidade, solidão, desenraizamento e construção de novos projetos de vida.'},
            {'q': 'Quanto dura uma sessão e quanto custa?', 'a': 'A sessão individual dura 45 minutos. Também existe uma modalidade com valor flexível, de uma hora, a partir de 40 €. Para valores exatos e disponibilidade, escreva diretamente ao profissional.'},
            {'q': 'Como escolho o profissional?', 'a': 'Você pode considerar o idioma, a modalidade, a disponibilidade e a apresentação de cada um. Se tiver dúvidas, escreva e te orientamos.'},
            {'q': 'Preciso saber explicar o que está acontecendo comigo?', 'a': 'Não. A primeira consulta também serve para começar a encontrar palavras para aquilo que preocupa ou causa sofrimento.'},
        ],
    },
    'contact': {
        'kicker': 'Contato direto',
        'title': 'Escolha com quem você quer começar.',
        'lead': 'Escreva por WhatsApp ou e-mail para combinar uma primeira consulta. Respondemos pessoalmente.',
        'people': [
            {'name': NAHUEL['name'], 'langs': 'Português · Español', 'wa': wa(NAHUEL['phone'], 'Olá Nahuel, gostaria de marcar uma primeira consulta.'), 'wa_label': 'WhatsApp · ' + NAHUEL['phone_display'], 'mail': mail(NAHUEL['email'], 'Primeira consulta'), 'email': NAHUEL['email'], 'track': 'nahuel'},
            {'name': SOL['name'], 'langs': 'Español · English', 'wa': wa(SOL['phone'], 'Hola Sol, me gustaría coordinar una primera consulta.'), 'wa_label': 'WhatsApp · ' + SOL['phone_display'], 'mail': mail(SOL['email'], 'Primera consulta'), 'email': SOL['email'], 'track': 'sol'},
        ],
    },
    'footer': {
        'tagline': 'Psicoterapia de orientação psicanalítica em Barcelona e online.',
        'legal': 'Profissionais com diploma homologado para exercer na Espanha.',
    },
    'dock': {'label': 'Marcar primeira consulta', 'href': '#contacto'},
}

PAGES = {'es': ES, 'en': EN, 'pt': PT}
