[build]
  publish = "public"
  functions = "netlify/functions"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
