// FISÚ — fuente única de contenido.
// Productos: solo los que aparecen fotografiados en el brand book. Los nombres son
// descriptivos (el brand book no nombra los productos): confirmar con la marca.

export const SITE = {
  // Dominio final: reemplazar cuando esté definido. Se usa para canonical, OG y sitemap.
  url: 'https://www.fisuhelados.com.ar',
  base: '/fisu',
  name: 'FISÚ Helados',
  // Datos de contacto: REEMPLAZAR por los reales.
  whatsapp: 'https://wa.me/5491100000000',
  email: 'hola@fisuhelados.com.ar',
  instagram: 'https://www.instagram.com/fisuhelados',
  instagramHandle: '@fisuhelados',
};

export const CATEGORIES = [
  { id: 'todos', label: 'Todos' },
  { id: 'postres', label: 'Postres' },
  { id: 'barras', label: 'Barras' },
  { id: 'familiares', label: 'Familiares' },
  { id: 'individuales', label: 'Individuales' },
];

// theme: pink (frutilla) · chocolate · vainilla · mix · blue
export const PRODUCTS = [
  {
    slug: 'pote-fisu', name: 'Pote FISÚ', short: 'Pote',
    flavors: ['Frutilla', 'Chocolate', 'Vainilla'],
    flavorLine: 'Frutilla, chocolate y vainilla',
    desc: 'Tres sabores en un pote. La cuchara la ponés vos.',
    long: 'El pote de siempre, con tres bochas que no se pelean: frutilla, chocolate y vainilla.',
    feels: ['Cremoso', 'Para compartir (o no)', 'Tres sabores'],
    format: 'Familiar', ideal: 'La mesa después de comer',
    cats: ['familiares'], tag: 'Familiar', theme: 'pink', tint: 'pink',
    img: 'pote-trio', pack: { img: 'pote-solo', title: 'El pote de lunares.', text: 'Rosa, blanco y con la gota FISÚ. Lo vas a reconocer en cualquier freezer.' },
  },
  {
    slug: 'bombon-helado', name: 'Bombón helado', short: 'Bombón',
    flavors: ['Vainilla', 'Baño de chocolate'],
    flavorLine: 'Vainilla con baño de chocolate',
    desc: 'Crujiente por fuera, cremoso por dentro. La primera mordida es la mejor.',
    long: 'Un bloque de helado bañado en chocolate, en su paquete de manchitas. De la mano a la boca, sin escalas.',
    feels: ['Baño crocante', 'Cremoso', 'De mano'],
    format: 'Individual', ideal: 'El antojo de la tarde',
    cats: ['barras', 'individuales'], tag: 'Individual', theme: 'blue', tint: 'choco',
    img: 'bombon-pack', pack: { img: 'bombon-pack', title: 'Paquete con manchitas.', text: 'Chocolate y crema por fuera también: así se ve el bombón FISÚ.' },
  },
  {
    slug: 'barra-crocante', name: 'Barra crocante', short: 'Barra',
    flavors: ['Chocolate', 'Crocante'],
    flavorLine: 'Chocolate con crocante',
    desc: 'Chocolate por todos lados y crocante en cada mordida.',
    long: 'Helado cremoso, baño de chocolate y crocante pegado por todas partes. Mirar bajo tu propio riesgo.',
    feels: ['Crocante', 'Chocolatoso', 'Intenso'],
    format: 'Individual', ideal: 'Ese antojo de las once',
    cats: ['barras', 'individuales'], tag: 'Barra', theme: 'chocolate', tint: 'blue',
    img: 'barra-crocante-b',
  },
  {
    slug: 'torta-helada-frutilla', name: 'Torta helada de frutilla', short: 'Torta de frutilla',
    flavors: ['Frutilla', 'Crema'],
    flavorLine: 'Frutilla y crema sobre base de galleta',
    desc: 'Capa de frutilla, centro cremoso y base crocante.',
    long: 'Arriba frutilla brillante, en el medio crema helada, abajo galleta. Ese “dame un pedacito” que termina siendo media torta.',
    feels: ['Frutal', 'Cremosa', 'Base crocante'],
    format: 'Familiar', ideal: 'Cumpleaños, domingos y martes',
    cats: ['postres', 'familiares'], tag: 'Torta', theme: 'pink', tint: 'pink',
    img: 'torta-frutilla-b',
  },
  {
    slug: 'postre-tricolor', name: 'Postre tricolor', short: 'Tricolor',
    flavors: ['Chocolate', 'Frutilla', 'Vainilla'],
    flavorLine: 'Chocolate, frutilla y vainilla',
    desc: 'Tres capas, salsa de chocolate y una decisión fácil.',
    long: 'Chocolate, frutilla y vainilla en capas, sobre base de galleta y con hilos de salsa de chocolate.',
    feels: ['Por capas', 'Con salsa', 'Para compartir'],
    format: 'Familiar', ideal: 'Cuando nadie se pone de acuerdo',
    cats: ['postres', 'familiares'], tag: 'Postre', theme: 'mix', tint: 'lilac',
    img: 'tricolor',
  },
  {
    slug: 'almendrado', name: 'Almendrado', short: 'Almendrado',
    flavors: ['Vainilla', 'Almendras'],
    flavorLine: 'Vainilla con crocante de almendras',
    desc: 'El clásico de sobremesa, con crocante de almendras.',
    long: 'Helado de vainilla cubierto de crocante de almendras. El clásico que nunca falla.',
    feels: ['Crocante', 'Tostado', 'Clásico'],
    format: 'Familiar', ideal: 'La sobremesa larga',
    cats: ['postres', 'familiares'], tag: 'Postre', theme: 'vainilla', tint: 'yellow',
    img: 'almendrado',
  },
  {
    slug: 'almendrado-chocolate', name: 'Almendrado con chocolate', short: 'Almendrado choco',
    flavors: ['Vainilla', 'Almendras', 'Chocolate'],
    flavorLine: 'Vainilla, crocante y salsa de chocolate',
    desc: 'Todo lo del almendrado, más chocolate. No hacía falta, pero gracias.',
    long: 'Vainilla helada con bordes de crocante y líneas de salsa de chocolate por encima.',
    feels: ['Crocante', 'Con salsa', 'Clásico mejorado'],
    format: 'Para compartir', ideal: 'Cuando el almendrado no alcanza',
    cats: ['postres', 'familiares'], tag: 'Postre', theme: 'vainilla', tint: 'cream',
    img: 'almendrado-choco',
  },
  {
    slug: 'bombon-con-crema', name: 'Bombón con crema', short: 'Bombón con crema',
    flavors: ['Chocolate', 'Crema', 'Cereza'],
    flavorLine: 'Chocolate, crema y cereza en canasta de oblea',
    desc: 'Una cúpula de chocolate, crema arriba y la cereza de corona.',
    long: 'Cúpula de helado bañada en chocolate, sobre canasta de oblea, con crema y una cereza.',
    feels: ['Festivo', 'Cremoso', 'Con oblea'],
    format: 'Individual', ideal: 'Ese postre después de comer',
    cats: ['postres', 'individuales'], tag: 'Individual', theme: 'chocolate', tint: 'choco',
    img: 'bombon-crema',
  },
  {
    slug: 'canasta-chocolate', name: 'Canasta de chocolate', short: 'Canasta',
    flavors: ['Chocolate', 'Almendras'],
    flavorLine: 'Chocolate con salsa y almendras',
    desc: 'Chocolate en canasta de oblea, con salsa y almendras.',
    long: 'Helado de chocolate en canasta de oblea, con salsa de chocolate, trocitos y almendras.',
    feels: ['Intenso', 'Con salsa', 'Crocante'],
    format: 'Individual', ideal: 'Un mal día (o uno bueno)',
    cats: ['postres', 'individuales'], tag: 'Individual', theme: 'chocolate', tint: 'blue',
    img: 'canasta-choco',
  },
  {
    slug: 'panqueque-helado', name: 'Panqueque helado', short: 'Panqueque',
    flavors: ['Vainilla', 'Chocolate', 'Frutilla'],
    flavorLine: 'Relleno helado con salsas de chocolate y frutilla',
    desc: 'Panqueque, helado y dos salsas. Postre de domingo, cualquier día.',
    long: 'Panqueque relleno de helado, con salsa de chocolate y salsa de frutilla por encima.',
    feels: ['Con salsas', 'Cremoso', 'De domingo'],
    format: 'Postre', ideal: 'El domingo, o cuando quieras que sea domingo',
    cats: ['postres'], tag: 'Postre', theme: 'vainilla', tint: 'yellow',
    img: 'panqueque',
  },
  {
    slug: 'canastitas', name: 'Canastitas', short: 'Canastitas',
    flavors: ['Frutilla', 'Chocolate', 'Vainilla'],
    flavorLine: 'Frutilla, chocolate y vainilla en oblea',
    desc: 'Tres canastitas de oblea, una de cada sabor.',
    long: 'Una bocha por canastita de oblea: frutilla, chocolate y vainilla. Difícil elegir una sola.',
    feels: ['Tres sabores', 'Con oblea', 'De a uno'],
    format: 'Individual', ideal: 'Probar de todo un poco',
    cats: ['individuales'], tag: 'Individual', theme: 'mix', tint: 'lilac',
    img: 'bochas',
  },
];

export const bySlug = Object.fromEntries(PRODUCTS.map(p => [p.slug, p]));
